### VALUES YOU SHOULD CHANGE ###

# GENERAL SITE SETTINGS
# title: This will be displayed as the website's name in your browser tab.
title: Vicen
# description: This will be meta HTML tag content. This can be ignored.
description: Personal website powered by Jekyll
# baseurl: The subpath of your site
# > set this to "", if you renamed the repository to <user>.github.io
baseurl: ""

# LANDING PAGE
# username: This will displayed on the landing page as your name.
username: Vicen
# typing_text: This will be typed before 'scroll down for more'.
# > set this to your job title, e.g. Fullstack Developer
typing_text: Pentesting Student
# email: Your E-Mail address for the email button.
email: vicenguzmann@gmail.com
# For every social button you want to display, set your username or userid
# If you do not use one of the following websites, then leave it empty
# > twitter_username:
github_username: vicenguzmann
codepen_username:
dev_username:
linkedin_username: vicen_guzmann
twitter_username:

# ABOUT ME SECTION
# show_aboutme_card:
# > setting this to true, will display the About Me section
# > setting this to false, will omit the About Me section
show_aboutme_card: true
# about_me_title: The will be displayed as the title in the About Me section
about_me_title: About me
about_me_description: |
  I'm a <strong>21-year-old student</strong> starting my journey into the fascinating world of <strong>pentesting and cybersecurity</strong>. 
  My passion for technology kicked off at the age of <strong>16</strong>, when I became curious about how networks and low-level communications worked, eager to understand what could I find under the surface of Internet.

  The time passed, and this curiosity evolved into a solid foundation in <strong>software development</strong>, leading me to become a <strong>full-stack developer</strong> based on languages like <strong>Java, ABAP, Python</strong>, and frameworks such as <strong>Node.js</strong> and <strong>React</strong>. 
  Software development taught me how to <strong>create</strong> but cybersecurity has tauthg me how to <strong>think</strong>.<br><br>
  <em>"In a world built on code, I don’t just write it. I break it to make it stronger. Just be patient, there is no exploit more powerful than consistency."</em>
# about_me_description: This will be displayed under the title.
#about_me_description: |
#  Soy un joven de 21 años que está comenzando su camino en el fascinante mundo del pentesting y la ciberseguridad. 
#  Mi pasión por la tecnología nació a los 16, cuando empecé a interesarme por cómo funcionaban las redes y las comunicaciones a bajo nivel, con ganas de entender qué había debajo de la superficie de lo digital.

#  Con el tiempo, esa curiosidad se transformó en una base sólida en el desarrollo de software, lo que me llevó a formarme como desarrollador fullstack, trabajando con lenguajes como Java, ABAP, Python, y frameworks como Node.js y React. 
#  Desarrollar software me enseñó a construir, pero la ciberseguridad me ha enseñado a pensar.

#  Hoy he decidido cambiar de rumbo y dedicarme a algo que considero realmente significativo: proteger sistemas y anticiparme a las amenazas en este campo digital que cambia constantemente.

#  "En un mundo construido con código, no solo lo escribo — lo rompo para hacerlo más fuerte."

#  Piensa en mí como un cerrajero digital: no solo abro puertas, sino que aprendo a construir mejores cerraduras.

#about_me_description: I'm a 21-year-old enthusiast at the beginning of my journey into the fascinating world of pentesting and cybersecurity. My passion for technology took root at the age of 16, when I became curious about how networks and low-level communications worked — eager to understand what lies beneath the surface of digital interactions. Over time, this curiosity evolved into a solid foundation in software development, leading me to become a full-stack developer proficient in languages like Java, ABAP, Python, and frameworks such as Node.js and React. Building software taught me how to create — but cybersecurity has taught me how to think. Today, I’ve shifted paths to pursue something I find deeply meaningful: securing systems and outsmarting threats in the ever-evolving digital battlefield.
# SKILLS SECTION
# show_skills_card:
# > setting this to true, will display the Skills section
# > setting this to false, will omit the Skills section
show_skills_card: true
# about_me_title: The will be displayed as the title in the Skills section
skills_title: Skills

# TIMELINE SECTION
# show_timeline_card:
# > setting this to true, will display the Timeline section
# > setting this to false, will omit the Timeline section
show_timeline_card: true
# timeline_title: The will be displayed as the title in the Timeline section
timeline_title: Education & Experience
# cv_download_link: The link where you host your cv.
# > e.g. you share your cv on your dropbox, then add the dropbox link here
cv_download_link: https://example.com/

# PROJECTS SECTION
# show_projects_card:
# > setting this to true, will display the Projects section
# > setting this to false, will omit the Projects section
show_projects_card: true
# show_projects:
# > setting this to true, will display your listed projects in _data/projects.yml
# > setting this to false, will omit your listed projects
show_projects: true
# projects_title: The will be displayed as the title of your projects
projects_title: Projects
# show_os_projects:
# > setting this to true, will display your public projects on github
# > setting this to false, will omit your public projects on github
show_os_projects: true
# os_projects_title: The will be displayed as the title of your open source projects
os_projects_title: Open Source Projects

# CONTACT SECTION
# show_contact_card:
# > setting this to true, will display the Contact section
# > setting this to false, will omit the Contact section
show_contact_card: true
# contact_title: The will be displayed as the title in the Contact section
contact_title: Contact
# contact_description: This will be displayed under the title.
contact_description: I'm always open to new opportunities, collaborations, or just a good chat about cybersecurity and technology. If you’d like to get in touch, feel free to reach out!
# GITHUB-METADATA
# Set this to your forked repository
# > e.g. <user>/<user>.github.io
repository: longpdo/neumorphism
projects:
  # sortby:
  # > set this to pushed, if you want to sort your github repositories by time.
  # > set this to stars, if you want to sort your github repositories by stars.
  sort_by: pushed
  exclude:
    # archived:
    # > setting this to true, will exclude archived repositories
    # > setting this to false, will also display archived repositories
    archived: true
    # forks:
    # > setting this to true, will exclude forked repositories
    # > setting this to false, will also display forked repositories
    forks: true
    # projects: A list of the repository names you want to exclude from the listing.
    projects:
    # - repo1-to-be-excluded
    # - repo2-to-be-excluded

# GOOGLE-ANALYTICS
# Set the id, if you want to track your website with Google Analytics
# > set this to "", if you do not want to track with Google Analytics
google-analytics:
  id: "UA-158757509-2"

### END OF VALUES YOU SHOULD CHANGE ###

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]

